In [120]:
# binary classification of data, Y if the loan is granted, N otherwise

import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('https://storage.googleapis.com/datasets-3456/loan_train_data.csv')

In [3]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [ ]:
df['ApplicantIncome']

In [ ]:
df['ApplicantIncome'] * 2

In [ ]:
df['ApplicantIncome'] > 5000

In [ ]:
df['ApplicantIncome'].loc[df['ApplicantIncome'] > 5000]

In [ ]:
df

In [ ]:
df['Property_Area']

In [4]:
df['Property_Area'].unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [ ]:
df['Property_Area'].value_counts()

In [ ]:
plt.bar([0, 1, 2], df['Property_Area'].value_counts())

In [ ]:
df['ApplicantIncome']

In [ ]:
plt.hist(df['ApplicantIncome'], bins=80)

In [ ]:
df['Gender'].unique() # NaN -> Not a Number

In [ ]:
df['GE'] = 0

In [ ]:
df

In [5]:
df.loc[df['Gender'] == 'Female', 'GE'] = 1
df.loc[df['Gender'] == 'Male', 'GE'] = 2

In [ ]:
df

In [6]:
df.drop(columns=['Loan_ID', 'Gender'], inplace=True)

In [ ]:
df

In [ ]:
df['Married'].value_counts()

In [7]:
df['Married'] = df['Married'].map({'No': 0, 'Yes': 1})

In [ ]:
df

In [ ]:
df['Dependents'].value_counts()

In [8]:
df['Dependents'] = df['Dependents'].map({'0': 0, '1': 1, '2': 2, '3+': 3})

In [ ]:
df

In [ ]:
df['Education'].value_counts()

In [9]:
df['Education'] = df['Education'].map({'Graduate': 1, 'Not Graduate':0})

In [ ]:
df

In [ ]:
df['Property_Area'].value_counts()

In [10]:
df = pd.get_dummies(df, columns=['Property_Area'])

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Married                  611 non-null    float64
 1   Dependents               599 non-null    float64
 2   Education                614 non-null    int64
 3   Self_Employed            582 non-null    object
 4   ApplicantIncome          614 non-null    int64
 5   CoapplicantIncome        614 non-null    float64
 6   LoanAmount               592 non-null    float64
 7   Loan_Amount_Term         600 non-null    float64
 8   Credit_History           564 non-null    float64
 9   Loan_Status              614 non-null    object
 10  GE                       601 non-null    float64
 11  Property_Area_Rural      614 non-null    bool
 12  Property_Area_Semiurban  614 non-null    bool
 13  Property_Area_Urban      614 non-null    bool
dtypes: bool(3), float64(7), int64(2), object(2)
memory usage: 54.7+ KB

In [ ]:
df['LoanAmount']

In [ ]:
df['LoanAmount'].mean()

In [ ]:
df['LoanAmount'].isna()

In [12]:
df.loc[df['LoanAmount'].isna(), 'LoanAmount'] = df['LoanAmount'].mean()

In [ ]:
df.info()

In [13]:
df.loc[df['Loan_Amount_Term'].isna(), 'Loan_Amount_Term'] = df['Loan_Amount_Term'].mean()

In [14]:
df.loc[df['Credit_History'].isna(), 'Credit_History'] = df['Credit_History'].mean()

In [15]:
df

,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,GE,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
0,0.0,0.0,1,No,5849,0.0,146.412162,360.0,1.0,Y,2.0,False,False,True
1,1.0,1.0,1,No,4583,1508.0,128.000000,360.0,1.0,N,2.0,True,False,False
2,1.0,0.0,1,Yes,3000,0.0,66.000000,360.0,1.0,Y,2.0,False,False,True
3,1.0,0.0,0,No,2583,2358.0,120.000000,360.0,1.0,Y,2.0,False,False,True
4,0.0,0.0,1,No,6000,0.0,141.000000,360.0,1.0,Y,2.0,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,0.0,0.0,1,No,2900,0.0,71.000000,360.0,1.0,Y,1.0,True,False,False
610,1.0,3.0,1,No,4106,0.0,40.000000,180.0,1.0,Y,2.0,True,False,False
611,1.0,1.0,1,No,8072,240.0,253.000000,360.0,1.0,Y,2.0,False,False,True
612,1.0,2.0,1,No,7583,0.0,187.000000,360.0,1.0,Y,2.0,False,False,True
613,0.0,0.0,1,Yes,4583,0.0,133.000000,360.0,0.0,N,1.0,False,True,False

In [16]:
X = df[ [
    'Married',
    'Dependents',
    'Education',
    'ApplicantIncome',
    'CoapplicantIncome',
    'LoanAmount',
    'Loan_Amount_Term',
    'Credit_History',
    'Property_Area_Rural',
    'Property_Area_Semiurban',
    'Property_Area_Urban',
] ]
X

,Married,Dependents,Education,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
0,0.0,0.0,1,5849,0.0,146.412162,360.0,1.0,False,False,True
1,1.0,1.0,1,4583,1508.0,128.000000,360.0,1.0,True,False,False
2,1.0,0.0,1,3000,0.0,66.000000,360.0,1.0,False,False,True
3,1.0,0.0,0,2583,2358.0,120.000000,360.0,1.0,False,False,True
4,0.0,0.0,1,6000,0.0,141.000000,360.0,1.0,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...
609,0.0,0.0,1,2900,0.0,71.000000,360.0,1.0,True,False,False
610,1.0,3.0,1,4106,0.0,40.000000,180.0,1.0,True,False,False
611,1.0,1.0,1,8072,240.0,253.000000,360.0,1.0,False,False,True
612,1.0,2.0,1,7583,0.0,187.000000,360.0,1.0,False,False,True
613,0.0,0.0,1,4583,0.0,133.000000,360.0,0.0,False,True,False

In [17]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Married                  611 non-null    float64
 1   Dependents               599 non-null    float64
 2   Education                614 non-null    int64
 3   ApplicantIncome          614 non-null    int64
 4   CoapplicantIncome        614 non-null    float64
 5   LoanAmount               614 non-null    float64
 6   Loan_Amount_Term         614 non-null    float64
 7   Credit_History           614 non-null    float64
 8   Property_Area_Rural      614 non-null    bool
 9   Property_Area_Semiurban  614 non-null    bool
 10  Property_Area_Urban      614 non-null    bool
dtypes: bool(3), float64(6), int64(2)
memory usage: 40.3 KB

In [18]:
X.loc[X['Dependents'].isna(), 'Dependents'] = X['Dependents'].mode()[0]

In [19]:
X.loc[X['Married'].isna(), 'Married'] = X['Married'].mode()[0]

In [20]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Married                  614 non-null    float64
 1   Dependents               614 non-null    float64
 2   Education                614 non-null    int64
 3   ApplicantIncome          614 non-null    int64
 4   CoapplicantIncome        614 non-null    float64
 5   LoanAmount               614 non-null    float64
 6   Loan_Amount_Term         614 non-null    float64
 7   Credit_History           614 non-null    float64
 8   Property_Area_Rural      614 non-null    bool
 9   Property_Area_Semiurban  614 non-null    bool
 10  Property_Area_Urban      614 non-null    bool
dtypes: bool(3), float64(6), int64(2)
memory usage: 40.3 KB

In [21]:
y = df['Loan_Status'].map({'Y': 1, 'N': 0})
y

0      1
1      0
2      1
3      1
4      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 614, dtype: int64

In [27]:
df

,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,GE,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
0,0.0,0.0,1,No,5849,0.0,146.412162,360.0,1.0,Y,2.0,False,False,True
1,1.0,1.0,1,No,4583,1508.0,128.000000,360.0,1.0,N,2.0,True,False,False
2,1.0,0.0,1,Yes,3000,0.0,66.000000,360.0,1.0,Y,2.0,False,False,True
3,1.0,0.0,0,No,2583,2358.0,120.000000,360.0,1.0,Y,2.0,False,False,True
4,0.0,0.0,1,No,6000,0.0,141.000000,360.0,1.0,Y,2.0,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,0.0,0.0,1,No,2900,0.0,71.000000,360.0,1.0,Y,1.0,True,False,False
610,1.0,3.0,1,No,4106,0.0,40.000000,180.0,1.0,Y,2.0,True,False,False
611,1.0,1.0,1,No,8072,240.0,253.000000,360.0,1.0,Y,2.0,False,False,True
612,1.0,2.0,1,No,7583,0.0,187.000000,360.0,1.0,Y,2.0,False,False,True
613,0.0,0.0,1,Yes,4583,0.0,133.000000,360.0,0.0,N,1.0,False,True,False

In [28]:
X

,Married,Dependents,Education,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
0,0.0,0.0,1,5849,0.0,146.412162,360.0,1.0,False,False,True
1,1.0,1.0,1,4583,1508.0,128.000000,360.0,1.0,True,False,False
2,1.0,0.0,1,3000,0.0,66.000000,360.0,1.0,False,False,True
3,1.0,0.0,0,2583,2358.0,120.000000,360.0,1.0,False,False,True
4,0.0,0.0,1,6000,0.0,141.000000,360.0,1.0,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...
609,0.0,0.0,1,2900,0.0,71.000000,360.0,1.0,True,False,False
610,1.0,3.0,1,4106,0.0,40.000000,180.0,1.0,True,False,False
611,1.0,1.0,1,8072,240.0,253.000000,360.0,1.0,False,False,True
612,1.0,2.0,1,7583,0.0,187.000000,360.0,1.0,False,False,True
613,0.0,0.0,1,4583,0.0,133.000000,360.0,0.0,False,True,False

In [29]:
y

0      1
1      0
2      1
3      1
4      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 614, dtype: int64

In [143]:
# output binar, task de clasificare
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier # diferite modele si metode de machine learning

from sklearn.model_selection import train_test_split # pentru splituirea datelor in date de antrenare si date de testare

from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.model_selection import cross_val_score # cross validation

from sklearn.model_selection import GridSearchCV # hyperparameter tuning

from sklearn.ensemble import VotingClassifier # se voteaza care model este mai bun

from imblearn.over_sampling import SMOTE # for unbalanced data, over-sampling the minority and under-sampling the majority class
from imblearn.under_sampling import RandomUnderSampler

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15)

# pentru balancing, in cazul la unbalanced dataset

smote = SMOTE()
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

In [94]:
model = KNeighborsClassifier()
model.fit(X_train, y_train)
print(model.score(X_test, y_test))

0.6129032258064516

In [182]:
model = RandomForestClassifier()
model.fit(X_train_smote, y_train_smote) # smote este pentru unbalanced data
print(model.score(X_test, y_test))

0.7419354838709677

In [97]:
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
print(model.score(X_test, y_test))

0.6774193548387096

In [115]:
model = GradientBoostingClassifier()
model.fit(X_train, y_train)
print(model.score(X_test, y_test))

0.7634408602150538

In [96]:
model = SVC()
model.fit(X_train, y_train)
print(model.score(X_test, y_test))

0.5913978494623656

In [106]:
model = MLPClassifier()
model.fit(X_train, y_train)
print(model.score(X_test, y_test))

0.6236559139784946

In [154]:
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'ROC AUC: {roc_auc}')

Accuracy: 0.7204301075268817
ROC AUC: 0.6693548387096775

In [153]:
scores = cross_val_score(model, X_train, y_train, cv=5, scoring='roc_auc')
print(f'Cross-validated ROC AUC scores: {scores}')

Cross-validated ROC AUC scores: [0.80723906 0.75130208 0.77886285 0.7875434  0.76106771]

In [155]:
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10]
}
grid_search = GridSearchCV(RandomForestClassifier(), param_grid, cv=5, scoring='roc_auc')
grid_search.fit(X_train, y_train)

grid_search.score(X_test, y_test)

0.7695109261186265

In [180]:
model1 = RandomForestClassifier()
model2 = DecisionTreeClassifier()
model3 = GradientBoostingClassifier()

voting_clf = VotingClassifier(estimators=[('rf', model1), ('dt', model2), ('gb', model3)], voting='soft')
voting_clf.fit(X_train, y_train)

voting_clf.score(X_test, y_test)

0.7419354838709677

In [183]:
# varianta de neural network

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Check for NaN or infinity values in X_train
print(np.any(np.isnan(X_train)))  # Check for NaN values
print(np.any(np.isinf(X_train)))  # Check for infinity values

# Handle both NaN and infinity values
X_train = X_train.replace([np.inf, -np.inf], np.nan)  # Replace infinity with NaN
X_train = X_train.fillna(0)  # Replace NaN with 0

# Convert X_train and y_train to TensorFlow tensors, ensuring float32 dtype
X_train_tensor = tf.convert_to_tensor(X_train.values.astype(np.float32))  # Convert to float32
y_train_tensor = tf.convert_to_tensor(y_train.values.astype(np.float32))  # Convert to float32

# Convert X_test to a tensor, similar to X_train
X_test_tensor = tf.convert_to_tensor(X_test.values.astype(np.float32))

model = Sequential()
model.add(Dense(64, input_dim=X_train_tensor.shape[1], activation='relu'))
model.add(Dense(32, activation='relu')) # relu pentru activare hidden layer
model.add(Dense(1, activation='sigmoid')) # sigmoid pentru clasificare binara

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Use X_test_tensor for validation
model.fit(X_train_tensor, y_train_tensor, epochs=100, batch_size=32, validation_data=(X_test_tensor, y_test))

False
False
Epoch 1/100
17/17 [==============================] - 2s 25ms/step - loss: 87.1737 - accuracy: 0.5413 - val_loss: 35.3962 - val_accuracy: 0.6774
Epoch 2/100
17/17 [==============================] - 0s 8ms/step - loss: 29.5201 - accuracy: 0.5816 - val_loss: 20.2018 - val_accuracy: 0.6667
Epoch 3/100
17/17 [==============================] - 0s 7ms/step - loss: 18.3810 - accuracy: 0.5605 - val_loss: 12.1280 - val_accuracy: 0.4946
Epoch 4/100
17/17 [==============================] - 0s 8ms/step - loss: 13.1050 - accuracy: 0.5259 - val_loss: 11.1705 - val_accuracy: 0.6774
Epoch 5/100
17/17 [==============================] - 0s 8ms/step - loss: 13.7640 - accuracy: 0.5835 - val_loss: 6.0805 - val_accuracy: 0.5484
Epoch 6/100
17/17 [==============================] - 0s 8ms/step - loss: 7.3135 - accuracy: 0.5720 - val_loss: 10.0299 - val_accuracy: 0.6882
Epoch 7/100
17/17 [==============================] - 0s 8ms/step - loss: 14.6870 - accuracy: 0.6315 - val_loss: 8.9385 - val_accuracy: 0.6129
Epoch 8/100
17/17 [==============================] - 0s 9ms/step - loss: 8.5502 - accuracy: 0.5605 - val_loss: 5.6332 - val_accuracy: 0.6559
Epoch 9/100
17/17 [==============================] - 0s 9ms/step - loss: 7.9946 - accuracy: 0.5720 - val_loss: 6.0355 - val_accuracy: 0.5806
Epoch 10/100
17/17 [==============================] - 0s 6ms/step - loss: 4.9556 - accuracy: 0.5969 - val_loss: 8.6363 - val_accuracy: 0.6452
Epoch 11/100
17/17 [==============================] - 0s 10ms/step - loss: 12.0688 - accuracy: 0.6372 - val_loss: 25.5695 - val_accuracy: 0.3978
Epoch 12/100
17/17 [==============================] - 0s 11ms/step - loss: 29.6205 - accuracy: 0.5777 - val_loss: 26.6669 - val_accuracy: 0.4086
Epoch 13/100
17/17 [==============================] - 0s 12ms/step - loss: 8.0390 - accuracy: 0.6180 - val_loss: 9.8172 - val_accuracy: 0.5054
Epoch 14/100
17/17 [==============================] - 0s 14ms/step - loss: 4.8607 - accuracy: 0.6161 - val_loss: 8.7063 - val_accuracy: 0.4194
Epoch 15/100
17/17 [==============================] - 0s 11ms/step - loss: 5.9941 - accuracy: 0.6180 - val_loss: 6.4754 - val_accuracy: 0.4839
Epoch 16/100
17/17 [==============================] - 0s 8ms/step - loss: 4.2979 - accuracy: 0.6065 - val_loss: 2.7360 - val_accuracy: 0.6989
Epoch 17/100
17/17 [==============================] - 0s 17ms/step - loss: 4.6525 - accuracy: 0.6161 - val_loss: 5.3647 - val_accuracy: 0.6774
Epoch 18/100
17/17 [==============================] - 0s 14ms/step - loss: 9.3808 - accuracy: 0.5950 - val_loss: 11.5140 - val_accuracy: 0.4409
Epoch 19/100
17/17 [==============================] - 0s 19ms/step - loss: 9.1545 - accuracy: 0.5585 - val_loss: 16.6716 - val_accuracy: 0.6882
Epoch 20/100
17/17 [==============================] - 0s 7ms/step - loss: 11.0330 - accuracy: 0.5873 - val_loss: 8.9197 - val_accuracy: 0.6882
Epoch 21/100
17/17 [==============================] - 0s 10ms/step - loss: 10.2610 - accuracy: 0.5835 - val_loss: 7.9962 - val_accuracy: 0.6667
Epoch 22/100
17/17 [==============================] - 0s 17ms/step - loss: 4.8199 - accuracy: 0.6161 - val_loss: 11.4502 - val_accuracy: 0.3763
Epoch 23/100
17/17 [==============================] - 0s 20ms/step - loss: 5.9978 - accuracy: 0.6142 - val_loss: 3.3230 - val_accuracy: 0.6882
Epoch 24/100
17/17 [==============================] - 0s 20ms/step - loss: 5.2471 - accuracy: 0.5758 - val_loss: 3.8834 - val_accuracy: 0.6667
Epoch 25/100
17/17 [==============================] - 0s 22ms/step - loss: 2.6400 - accuracy: 0.6430 - val_loss: 5.8943 - val_accuracy: 0.4409
Epoch 26/100
17/17 [==============================] - 0s 29ms/step - loss: 6.5867 - accuracy: 0.5797 - val_loss: 8.9514 - val_accuracy: 0.6667
Epoch 27/100
17/17 [==============================] - 0s 16ms/step - loss: 8.7158 - accuracy: 0.6180 - val_loss: 22.1750 - val_accuracy: 0.4194
Epoch 28/100
17/17 [==============================] - 0s 12ms/step - loss: 10.5650 - accuracy: 0.6468 - val_loss: 8.3466 - val_accuracy: 0.6559
Epoch 29/100
17/17 [==============================] - 0s 21ms/step - loss: 8.0733 - accuracy: 0.6180 - val_loss: 5.0877 - val_accuracy: 0.6882
Epoch 30/100
17/17 [==============================] - 0s 14ms/step - loss: 3.9638 - accuracy: 0.6257 - val_loss: 2.6636 - val_accuracy: 0.5591
Epoch 31/100
17/17 [==============================] - 0s 17ms/step - loss: 2.5699 - accuracy: 0.6372 - val_loss: 13.4766 - val_accuracy: 0.6774
Epoch 32/100
17/17 [==============================] - 0s 19ms/step - loss: 23.5285 - accuracy: 0.5912 - val_loss: 18.1560 - val_accuracy: 0.6774
Epoch 33/100
17/17 [==============================] - 0s 10ms/step - loss: 10.4875 - accuracy: 0.5624 - val_loss: 5.3053 - val_accuracy: 0.6559
Epoch 34/100
17/17 [==============================] - 0s 18ms/step - loss: 4.7059 - accuracy: 0.6180 - val_loss: 23.4489 - val_accuracy: 0.4301
Epoch 35/100
17/17 [==============================] - 0s 12ms/step - loss: 11.5631 - accuracy: 0.5893 - val_loss: 9.2772 - val_accuracy: 0.6559
Epoch 36/100
17/17 [==============================] - 0s 8ms/step - loss: 7.3980 - accuracy: 0.6065 - val_loss: 8.3361 - val_accuracy: 0.6452
Epoch 37/100
17/17 [==============================] - 0s 12ms/step - loss: 12.4573 - accuracy: 0.6123 - val_loss: 13.0518 - val_accuracy: 0.3656
Epoch 38/100
17/17 [==============================] - 0s 8ms/step - loss: 4.5398 - accuracy: 0.5643 - val_loss: 4.7492 - val_accuracy: 0.6882
Epoch 39/100
17/17 [==============================] - 0s 9ms/step - loss: 5.7086 - accuracy: 0.6257 - val_loss: 11.5585 - val_accuracy: 0.6667
Epoch 40/100
17/17 [==============================] - 0s 9ms/step - loss: 4.5197 - accuracy: 0.6008 - val_loss: 14.8017 - val_accuracy: 0.3763
Epoch 41/100
17/17 [==============================] - 0s 8ms/step - loss: 9.7146 - accuracy: 0.5605 - val_loss: 6.4293 - val_accuracy: 0.6667
Epoch 42/100
17/17 [==============================] - 0s 8ms/step - loss: 6.9594 - accuracy: 0.5835 - val_loss: 5.8414 - val_accuracy: 0.4194
Epoch 43/100
17/17 [==============================] - 0s 12ms/step - loss: 3.6990 - accuracy: 0.6200 - val_loss: 7.0454 - val_accuracy: 0.6452
Epoch 44/100
17/17 [==============================] - 0s 8ms/step - loss: 5.1450 - accuracy: 0.6219 - val_loss: 3.8269 - val_accuracy: 0.4839
Epoch 45/100
17/17 [==============================] - 0s 9ms/step - loss: 5.8152 - accuracy: 0.6353 - val_loss: 7.6415 - val_accuracy: 0.4516
Epoch 46/100
17/17 [==============================] - 0s 10ms/step - loss: 5.6428 - accuracy: 0.6276 - val_loss: 13.4506 - val_accuracy: 0.3548
Epoch 47/100
17/17 [==============================] - 0s 10ms/step - loss: 8.0466 - accuracy: 0.5643 - val_loss: 18.4444 - val_accuracy: 0.3333
Epoch 48/100
17/17 [==============================] - 0s 10ms/step - loss: 7.1284 - accuracy: 0.5797 - val_loss: 6.5272 - val_accuracy: 0.4946
Epoch 49/100
17/17 [==============================] - 0s 11ms/step - loss: 3.2855 - accuracy: 0.6430 - val_loss: 7.8954 - val_accuracy: 0.3978
Epoch 50/100
17/17 [==============================] - 0s 7ms/step - loss: 4.3046 - accuracy: 0.5988 - val_loss: 11.2959 - val_accuracy: 0.6667
Epoch 51/100
17/17 [==============================] - 0s 8ms/step - loss: 9.9265 - accuracy: 0.5893 - val_loss: 3.3780 - val_accuracy: 0.5484
Epoch 52/100
17/17 [==============================] - 0s 7ms/step - loss: 2.8638 - accuracy: 0.6622 - val_loss: 4.4114 - val_accuracy: 0.6774
Epoch 53/100
17/17 [==============================] - 0s 11ms/step - loss: 3.3373 - accuracy: 0.6257 - val_loss: 3.3311 - val_accuracy: 0.6452
Epoch 54/100
17/17 [==============================] - 0s 12ms/step - loss: 3.8398 - accuracy: 0.6200 - val_loss: 3.0585 - val_accuracy: 0.6559
Epoch 55/100
17/17 [==============================] - 0s 7ms/step - loss: 6.3495 - accuracy: 0.6142 - val_loss: 24.5854 - val_accuracy: 0.3441
Epoch 56/100
17/17 [==============================] - 0s 21ms/step - loss: 11.4501 - accuracy: 0.5950 - val_loss: 7.7507 - val_accuracy: 0.6559
Epoch 57/100
17/17 [==============================] - 0s 23ms/step - loss: 6.3484 - accuracy: 0.6315 - val_loss: 14.1259 - val_accuracy: 0.6559
Epoch 58/100
17/17 [==============================] - 0s 4ms/step - loss: 5.2978 - accuracy: 0.6238 - val_loss: 2.4675 - val_accuracy: 0.5699
Epoch 59/100
17/17 [==============================] - 0s 5ms/step - loss: 2.1457 - accuracy: 0.6468 - val_loss: 3.6906 - val_accuracy: 0.5806
Epoch 60/100
17/17 [==============================] - 0s 5ms/step - loss: 4.8983 - accuracy: 0.5662 - val_loss: 7.0056 - val_accuracy: 0.4301
Epoch 61/100
17/17 [==============================] - 0s 4ms/step - loss: 4.9828 - accuracy: 0.5835 - val_loss: 8.8282 - val_accuracy: 0.6667
Epoch 62/100
17/17 [==============================] - 0s 4ms/step - loss: 18.1108 - accuracy: 0.6430 - val_loss: 9.7794 - val_accuracy: 0.6774
Epoch 63/100
17/17 [==============================] - 0s 4ms/step - loss: 7.9529 - accuracy: 0.6142 - val_loss: 18.9396 - val_accuracy: 0.6882
Epoch 64/100
17/17 [==============================] - 0s 5ms/step - loss: 8.3138 - accuracy: 0.5854 - val_loss: 14.8738 - val_accuracy: 0.6129
Epoch 65/100
17/17 [==============================] - 0s 5ms/step - loss: 11.1983 - accuracy: 0.5317 - val_loss: 4.6965 - val_accuracy: 0.6667
Epoch 66/100
17/17 [==============================] - 0s 4ms/step - loss: 3.3470 - accuracy: 0.6353 - val_loss: 2.4949 - val_accuracy: 0.6344
Epoch 67/100
17/17 [==============================] - 0s 4ms/step - loss: 4.6085 - accuracy: 0.6027 - val_loss: 9.1917 - val_accuracy: 0.4194
Epoch 68/100
17/17 [==============================] - 0s 5ms/step - loss: 11.2616 - accuracy: 0.5758 - val_loss: 2.0055 - val_accuracy: 0.5914
Epoch 69/100
17/17 [==============================] - 0s 4ms/step - loss: 2.3193 - accuracy: 0.6718 - val_loss: 2.3311 - val_accuracy: 0.5914
Epoch 70/100
17/17 [==============================] - 0s 6ms/step - loss: 2.1927 - accuracy: 0.6660 - val_loss: 3.4831 - val_accuracy: 0.4409
Epoch 71/100
17/17 [==============================] - 0s 5ms/step - loss: 8.5026 - accuracy: 0.6008 - val_loss: 12.7315 - val_accuracy: 0.6559
Epoch 72/100
17/17 [==============================] - 0s 5ms/step - loss: 6.1326 - accuracy: 0.5931 - val_loss: 11.2025 - val_accuracy: 0.3978
Epoch 73/100
17/17 [==============================] - 0s 6ms/step - loss: 3.4413 - accuracy: 0.6315 - val_loss: 9.7703 - val_accuracy: 0.4086
Epoch 74/100
17/17 [==============================] - 0s 6ms/step - loss: 8.6532 - accuracy: 0.5643 - val_loss: 11.7871 - val_accuracy: 0.4086
Epoch 75/100
17/17 [==============================] - 0s 4ms/step - loss: 3.5839 - accuracy: 0.6699 - val_loss: 5.2982 - val_accuracy: 0.6129
Epoch 76/100
17/17 [==============================] - 0s 4ms/step - loss: 3.5608 - accuracy: 0.5912 - val_loss: 3.5542 - val_accuracy: 0.6452
Epoch 77/100
17/17 [==============================] - 0s 5ms/step - loss: 3.6294 - accuracy: 0.6411 - val_loss: 5.5963 - val_accuracy: 0.3763
Epoch 78/100
17/17 [==============================] - 0s 5ms/step - loss: 8.4187 - accuracy: 0.5624 - val_loss: 2.7438 - val_accuracy: 0.5699
Epoch 79/100
17/17 [==============================] - 0s 6ms/step - loss: 4.4063 - accuracy: 0.6257 - val_loss: 4.8484 - val_accuracy: 0.6452
Epoch 80/100
17/17 [==============================] - 0s 5ms/step - loss: 7.3013 - accuracy: 0.5893 - val_loss: 5.9456 - val_accuracy: 0.6774
Epoch 81/100
17/17 [==============================] - 0s 5ms/step - loss: 5.1683 - accuracy: 0.5739 - val_loss: 5.0652 - val_accuracy: 0.6452
Epoch 82/100
17/17 [==============================] - 0s 5ms/step - loss: 4.9062 - accuracy: 0.6180 - val_loss: 3.4184 - val_accuracy: 0.6667
Epoch 83/100
17/17 [==============================] - 0s 4ms/step - loss: 1.5949 - accuracy: 0.6372 - val_loss: 2.4146 - val_accuracy: 0.6559
Epoch 84/100
17/17 [==============================] - 0s 4ms/step - loss: 1.7240 - accuracy: 0.6468 - val_loss: 3.5379 - val_accuracy: 0.6774
Epoch 85/100
17/17 [==============================] - 0s 5ms/step - loss: 2.7874 - accuracy: 0.6430 - val_loss: 8.2514 - val_accuracy: 0.6559
Epoch 86/100
17/17 [==============================] - 0s 5ms/step - loss: 6.1879 - accuracy: 0.6276 - val_loss: 18.6100 - val_accuracy: 0.4301
Epoch 87/100
17/17 [==============================] - 0s 5ms/step - loss: 6.6896 - accuracy: 0.5873 - val_loss: 6.8312 - val_accuracy: 0.6559
Epoch 88/100
17/17 [==============================] - 0s 5ms/step - loss: 3.0363 - accuracy: 0.6449 - val_loss: 3.4731 - val_accuracy: 0.6774
Epoch 89/100
17/17 [==============================] - 0s 4ms/step - loss: 2.0059 - accuracy: 0.6468 - val_loss: 7.0894 - val_accuracy: 0.6452
Epoch 90/100
17/17 [==============================] - 0s 4ms/step - loss: 3.3580 - accuracy: 0.6180 - val_loss: 7.7146 - val_accuracy: 0.3978
Epoch 91/100
17/17 [==============================] - 0s 5ms/step - loss: 2.2404 - accuracy: 0.6449 - val_loss: 3.8914 - val_accuracy: 0.6559
Epoch 92/100
17/17 [==============================] - 0s 4ms/step - loss: 5.7341 - accuracy: 0.6142 - val_loss: 6.5319 - val_accuracy: 0.3871
Epoch 93/100
17/17 [==============================] - 0s 6ms/step - loss: 8.3085 - accuracy: 0.5739 - val_loss: 7.4059 - val_accuracy: 0.6882
Epoch 94/100
17/17 [==============================] - 0s 6ms/step - loss: 5.8338 - accuracy: 0.6296 - val_loss: 7.4181 - val_accuracy: 0.4516
Epoch 95/100
17/17 [==============================] - 0s 4ms/step - loss: 7.4313 - accuracy: 0.6084 - val_loss: 10.7145 - val_accuracy: 0.6667
Epoch 96/100
17/17 [==============================] - 0s 5ms/step - loss: 10.8271 - accuracy: 0.6545 - val_loss: 14.7989 - val_accuracy: 0.3978
Epoch 97/100
17/17 [==============================] - 0s 5ms/step - loss: 6.9392 - accuracy: 0.6123 - val_loss: 12.8357 - val_accuracy: 0.6344
Epoch 98/100
17/17 [==============================] - 0s 5ms/step - loss: 6.4103 - accuracy: 0.6027 - val_loss: 3.2011 - val_accuracy: 0.6559
Epoch 99/100
17/17 [==============================] - 0s 5ms/step - loss: 2.9404 - accuracy: 0.6372 - val_loss: 4.2513 - val_accuracy: 0.3871
Epoch 100/100
17/17 [==============================] - 0s 4ms/step - loss: 3.0152 - accuracy: 0.6641 - val_loss: 15.0410 - val_accuracy: 0.4194